name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses6 libncursesw6 libtinfo6 cmake libssl-dev
          # We use a specific version of Cython compatible with Kivy/Buildozer
          pip install --user --upgrade buildozer "cython<3.0.0" virtualenv

      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          
          # We DO NOT run 'clean' here because the GitHub runner is already clean.
          # We run the build directly.
          buildozer -v android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BookingApp-Debug-APK
          path: bin/*.apk
